apiVersion: v1
items:
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      field.cattle.io/creatorId: user-njndg
    creationTimestamp: 2018-10-31T17:35:13Z
    generation: 1
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: deployment-snapass-redis
    name: redis
    namespace: snapass
    resourceVersion: "2650"
    selfLink: /apis/extensions/v1beta1/namespaces/snapass/deployments/redis
    uid: 52e7a182-dd33-11e8-b6e5-0a5afa06bfae
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-snapass-redis
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: 2018-10-31T17:35:07Z
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: deployment-snapass-redis
      spec:
        containers:
        - image: redis:latest
          imagePullPolicy: Always
          name: redis
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2018-10-31T17:35:19Z
      lastUpdateTime: 2018-10-31T17:35:19Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2018-10-31T17:35:13Z
      lastUpdateTime: 2018-10-31T17:35:19Z
      message: ReplicaSet "redis-8f9cd9854" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 1
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      deployment.kubernetes.io/revision: "1"
      field.cattle.io/creatorId: user-njndg
      field.cattle.io/publicEndpoints: '[{"addresses":["18.206.236.104"],"port":80,"protocol":"HTTP","serviceName":"snapass:ingress-2fb069735e04655e7ffe34511907e057","ingressName":"snapass:snap","hostname":"snap.bombbomb.io","path":"/","allNodes":true}]'
    creationTimestamp: 2018-10-31T17:37:01Z
    generation: 2
    labels:
      cattle.io/creator: norman
      workload.user.cattle.io/workloadselector: deployment-snapass-snappass
    name: snappass
    namespace: snapass
    resourceVersion: "2918"
    selfLink: /apis/extensions/v1beta1/namespaces/snapass/deployments/snappass
    uid: 92cb3d3d-dd33-11e8-b6e5-0a5afa06bfae
  spec:
    progressDeadlineSeconds: 600
    replicas: 1
    revisionHistoryLimit: 10
    selector:
      matchLabels:
        workload.user.cattle.io/workloadselector: deployment-snapass-snappass
    strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 0
      type: RollingUpdate
    template:
      metadata:
        annotations:
          cattle.io/timestamp: 2018-10-31T17:36:54Z
        creationTimestamp: null
        labels:
          workload.user.cattle.io/workloadselector: deployment-snapass-snappass
      spec:
        containers:
        - env:
          - name: NO_SSL
            value: "True"
          - name: REDIS_HOST
            value: redis
          image: jde5011/snappass
          imagePullPolicy: Always
          name: snappass
          resources: {}
          securityContext:
            allowPrivilegeEscalation: false
            capabilities: {}
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: false
          stdin: true
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          tty: true
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: 2018-10-31T17:37:31Z
      lastUpdateTime: 2018-10-31T17:37:31Z
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: "True"
      type: Available
    - lastTransitionTime: 2018-10-31T17:37:01Z
      lastUpdateTime: 2018-10-31T17:37:31Z
      message: ReplicaSet "snappass-74bbd8474f" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: "True"
      type: Progressing
    observedGeneration: 2
    readyReplicas: 1
    replicas: 1
    updatedReplicas: 1
kind: List
