apiVersion: apps/v1
kind: Deployment
metadata:
  name: snappass
  labels:
    app: snappass
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snappass
  template:
    metadata:
      labels:
        app: snappass
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - env:
        - name: NO_SSL
          value: "True"
        - name: REDIS_HOST
          value: redis
        name: snappass
        image: snappass:latestzs