apiVersion: apps/v1
kind: Deployment
metadata:
  name: snappass2
  labels:
    app: snappass2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: snappass2
  template:
    metadata:
      labels:
        app: snappass2
    spec:
      imagePullSecrets:
      - name: pipeline-docker-registry
      containers:
      - env:
        - name: NO_SSL
          value: "True"
        - name: REDIS_HOST
          value: redis
        name: snappass2
        image: snappass:latestzs